### ISSUE TITLE
AttributeError: 'VAE' object has no attribute 'clone' in forge_layerdiffusion.py

### ISSUE THREAD

**Issue by EtienneDosSantos** [layerdiffusion/sd-forge-layerdiffusion#1]
When I enable layer diffusion in sd-forge, it has no effect. The resulting image is not transparent and is identical to the one generated with layer diffusion disabled. The error occurs within the process_before_every_sampling() function in the forge_layerdiffusion.py script. Here's the relevant information:
``` PowerShell 
[Layer Diffusion] LayerMethod.FG_ONLY_ATTN
*** Error running process_before_every_sampling: E:\stable-diffusion-webui-forge\extensions\sd-forge-layerdiffusion\scripts\forge_layerdiffusion.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui-forge\modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "E:\stable-diffusion-webui-forge\extensions\sd-forge-layerdiffusion\scripts\forge_layerdiffusion.py", line 130, in process_before_every_sampling
        vae = p.sd_model.forge_objects.vae.clone()
    AttributeError: 'VAE' object has no attribute 'clone'
```
- Operating system: Windows 11

**Comment by layerdiffusion** [comment]
you need to update forge

**Comment by EtienneDosSantos** [comment]
Yes, just noticed. Thx! 😊👍
