### ISSUE TITLE
    AttributeError: 'VAE' object has no attribute 'clone'

### ISSUE THREAD

**Issue by Phrixus2023** [layerdiffusion/sd-forge-layerdiffusion#13]
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.14v1.8.0rc-latest-184-g43c9e3b5
Commit hash: 43c9e3b5ce1642073c7a9684e36b45489eeb4a49
Launching Web UI with arguments:
Total VRAM 24564 MB, total RAM 16174 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
ControlNet preprocessor location: D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\models\ControlNetPreprocessor
Loading weights [f99f3dec38] from D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\models\Stable-diffusion\realisticStockPhoto_v20.safetensors
2024-03-03 13:36:14,199 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 20.7s (prepare environment: 5.5s, import torch: 5.2s, import gradio: 1.6s, setup paths: 1.2s, initialize shared: 0.2s, other imports: 1.0s, load scripts: 3.1s, create ui: 0.8s, gradio launch: 1.8s).
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
loaded straight to GPU
To load target model SDXL
Begin to load 1 model
To load target model SDXLClipModel
Begin to load 1 model
Moving model(s) has taken 1.41 seconds
Model loaded in 16.3s (load weights from disk: 1.0s, forge instantiate config: 1.5s, forge load real models: 11.2s, calculate empty prompt: 2.5s).
[Layer Diffusion] LayerMethod.FG_ONLY_ATTN
*** Error running process_before_every_sampling: D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\extensions\sd-forge-layerdiffusion\scripts\forge_layerdiffusion.py
    Traceback (most recent call last):
      File "D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\extensions\sd-forge-layerdiffusion\scripts\forge_layerdiffusion.py", line 130, in process_before_every_sampling
        vae = p.sd_model.forge_objects.vae.clone()
    AttributeError: 'VAE' object has no attribute 'clone'

---

**Comment by SoloistWong** [comment]
i had the same problem.

**Comment by Yukinoshita-Yukinoe** [comment]
Update "Forge" to the latest

**Comment by alonsojr1980** [comment]
> Update "Forge" to the latest

That fixes it!

**Comment by Mikk702** [comment]
I'm having the same problem. Everything is updated that I can tell. Any ideas?  

*** Error running process_before_every_sampling: D:\Ai\stable-diffusion-webui-forge-main\extensions\sd-forge-layerdiffusion\scripts\forge_layerdiffusion.py
    Traceback (most recent call last):
      File "D:\Ai\stable-diffusion-webui-forge-main\modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\Ai\stable-diffusion-webui-forge-main\extensions\sd-forge-layerdiffusion\scripts\forge_layerdiffusion.py", line 130, in process_before_every_sampling
        vae = p.sd_model.forge_objects.vae.clone()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'VAE' object has no attribute 'clone'

**Comment by baedesigns** [comment]
i am having this issue as well. I think it is the checkpoint model being used. For instance, I have two Flux Dev models. I think flux dev fp8 works with checkpoint loader, the flux dev1 works for unet diffusor node. if that makes sense.
